export const keyboardMap = {
    _Q: "C3",
    _2: "C#3",
    _W: "D3",
    _3: "D#3",
    _E: "E3",
    _R: "F3",
    _5: "F#3",
    _T: "G3",
    _6: "G#3",
    _Y: "A3",
    _7: "A#3",
    _U: "B3",
    _I: "C4",
    _9: "C#4",
    _O: "D4",
    _0: "D#4",
    _P: "E4",
    _Z: "F4",
    _S: "F#4",
    _X: "G4",
    _D: "G#4",
    _C: "A4",
    _F: "A#4",
    _V: "B4",
    _B: "C5",
    _H: "C#5",
    _N: "D5",
    _J: "D#5",
    _M: "E5",
    "_,": "F5",
    _L: "F#5",
    "_.": "G5",
    "_;": "G#5",
    "_/": "A5",
    "_'": "A#5",
    _A: "B5"
}
var AudioContext = window.AudioContext || window.webkitAudioContext;
export const audio = new AudioContext();